routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('tasks','TasksController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name','description','due_date','user_id','status'];

    protected $dates = [
        'due_date'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home')->with('tasks',Task::paginate(10));
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Task;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('task.index')->with('tasks',Task::paginate(10));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('task.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTaskRequest $request)
    {
        Task::create([
           'name' => $request->name,
           'description' => $request->description,
           'due_date' => $request->due_date,
           'user_id' => $request->user_id,
           'status' => 'unassigned'
       ]);
       return redirect()->route('home');

   
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        return view('task.create')->with('task',$task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTaskRequest $request, Task $task)
    {
        
        $task->update([
           'name' => $request->name,
           'description' => $request->description,
           'due_date' => $request->due_date,
           'user_id' => $request->user_id,
           'status' => 'unassigned'
        ]);
        
        return redirect(route('home'));

       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $task->delete();
        return redirect(route('home'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('title')
Dashboard
@endsection
@section('content')
<section id="services" class="section-bg">
  <div class="container">
    <div class="row">

      

      <div class="col-md-6 col-lg-5 offset-lg-1 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
        <div class="box">
          <div class="icon"><i class="ion-ios-paper-outline" style="color: #3fcdc7;"></i></div>
          <h4 class="title"><a href="{{ route('tasks.index') }}">All Tasks</a></h4>
          <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-5 wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
        <div class="box">
          <div class="icon"><i class="ion-ios-speedometer-outline" style="color:#41cf2e;"></i></div>
          <h4 class="title"><a href="">Employee</a></h4>
          <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est </p>
        </div>
      </div>

      

    </div>

  </div>
</section>
<!-- #services -->
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Managify Employee Management</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="img/favicon.png" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet"> 
  

  <!-- Bootstrap CSS File -->
  <link href="{{asset('theme/lib/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{{asset('theme/lib/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
  <link href="{{asset('theme/lib/animate/animate.min.css')}}" rel="stylesheet">
  <link href="{{asset('theme/lib/ionicons/css/ionicons.min.css')}}" rel="stylesheet">
  <link href="{{asset('theme/lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
  <link href="{{asset('theme/lib/lightbox/css/lightbox.min.css')}}" rel="stylesheet">
  @yield('css')

  <!-- Main Stylesheet File -->
  <link href="{{asset('theme/css/style.css')}}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: NewBiz
    Theme URL: https://bootstrapmade.com/newbiz-bootstrap-business-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body>

  <!--==========================
  Header
  ============================-->
  <header id="header" class="fixed-top">
    <div class="container">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <h1 class="text-light"><a href="#header"><span>NewBiz</span></a></h1> -->
        <a href="{{ route('welcome') }}" class="scrollto"><img src="theme/img/managify_logo.png" alt="" class="img-fluid"></a>
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="{{ route('home') }}">Dashboard</a></li>
          
        <li class="drop-down"><a href="">
            @auth
            {{ Auth::user()->name }}
            @else
            Login
            @endauth
        </a>
            <ul>
              <li><a href=""{{ route('logout') }}"
                onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">LOG OUT</a></li>
                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                        </form>  
              <li><a href="#">Drop Down 3</a></li>
            </ul>
          </li>
          
        </ul>
      </nav><!-- .main-nav -->
      
    </div>
  </header><!-- #header -->

  <!--==========================
    Intro Section
  ============================-->
  <section id="intro" class="clearfix">
        <header class="section-header">
                <h3  style="color:white;">
                @yield('title')
                </h3>
        </header>
    
  </section><!-- #intro -->

  <main id="main">

    <!--==========================
      Services Section
    ============================-->
   @yield('content')

  

  
 



  
    <!--==========================
      Contact Section
    ============================-->

  </main>

  <!--==========================
    Footer
  ============================-->
  <!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

  <!-- JavaScript Libraries -->
  <script src="{{asset('theme/lib/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('theme/lib/jquery/jquery-migrate.min.js')}}"></script>
  <script src="{{asset('theme/lib/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{asset('theme/lib/easing/easing.min.js')}}"></script>
  <script src="{{asset('theme/lib/mobile-nav/mobile-nav.js')}}"></script>
  <script src="{{asset('theme/lib/wow/wow.min.js')}}"></script>
  <script src="{{asset('theme/lib/waypoints/waypoints.min.js')}}"></script>
  <script src="{{asset('theme/lib/counterup/counterup.min.js')}}"></script>
  <script src="{{asset('theme/lib/owlcarousel/owl.carousel.min.js')}}"></script>
  <script src="{{asset('theme/lib/isotope/isotope.pkgd.min.js')}}"></script>
  <script src="{{asset('theme/lib/lightbox/js/lightbox.min.js')}}"></script>
  <!-- Contact Form JavaScript File -->
  <script src="{{asset('theme/contactform/contactform.js')}}"></script>

  <!-- Template Main Javascript File -->
  <script src="{{asset('theme/js/main.js')}}"></script>
  @yield('scripts')

</body>
</html>

resources/views/partials/errors.blade.php
@if($errors->any())
        <div class="alert alert-danger">
        <ul class="list-group">
        @foreach($errors->all() as $error)
        <li>{{$error}}</li>        
        @endforeach
        </ul>
        </div>
        @endif

resources/views/task/create.blade.php
@extends('layouts.app')
@section('title')
{{ isset($task) ? 'Update Task' : 'Create Task' }}
@endsection

@section('content')
<section id="contact">
        <div class="container-fluid">
          <div class="row wow fadeInUp">
  
            <div class="col-md-6 offset-md-3">
  
              <div class="form">
              
                <div id="errormessage">
                 
                </div>
              <form method="POST" action="{{isset($task) ? route('tasks.update',$task->id) : route('tasks.create')}}">
                    @csrf
                    @if(isset($task))
                      @method('put')
                    @endif

                  <div class="form-row">
                    <div class="form-group col-lg-8">
                      <label for="name">Task name</label>
                      <input type="text" name="name" class="form-control" id="name" placeholder="Task name"
                    @if(isset($task))
                      value="{{$task->name}}"
                    @endif
                    />
                    </div>
                    <div class="form-group col-lg-8">
                        <label for="description">Description</label>
                       <textarea name='description' class="form-control">@if(isset($task)){{$task->description}}@endif
                       </textarea>
                    </div>
                    <div class="form-group col-lg-8">
                        <label for="due_date">Due date</label>
                            <input type="text" class="form-control" id='due_date' name="due_date"
                          @if(isset($task))
                            value="{{$task->due_date}}"
                          @endif
                            >
                        </div>
                      



                    </div>
                    <div class="form-group col-lg-8">
                        <label for="user_id">Select a user</label>
                        <select class="form-control" name="user_id">
                          <option id="1" value="1">Reaz</option>
                          <option id="2" value="2">bambon</option>
                        </select>
                      </div>
                      <div class="form-group col-lg-8">
                          <button  type="submit" class="btn-common btn-edit text-center form-control">
                            {{ isset($task) ? 'Update' : 'Create Task' }}
                          </button>
                      </div>
                    
                    
                    
          
                 

                  
                </form>
              </div>
            </div>
  
          </div>
  
        </div>
      </section><!-- #contact -->
  

@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    flatpickr('#due_date', {
      
    });
</script> 
@endsection

resources/views/task/index.blade.php
@extends('layouts.app')

@section('title')
Tasks
@endsection
@section('content')
<section id="services" class="section-bg">
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4 text-center">
                <a href="{{route('tasks.create')}}" class="btn-common btn-edit text-center mb-4">Create a new task</a>
            </div>
          
        </div>
        <div class="row">
          <div class="col-12">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th scope="col">Due date</th>
                  <th scope="col">task Name</th>
                  <th scope="col">Author</th>
                  <th scope="col">Shares</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
          @foreach ($tasks as $task)
                <tr>
                  <th scope="row">{{ $task->due_date->toFormattedDateString() }}</th>
                  <td>{{ $task->name }}</td>
                  <td>Cristina</td>
                  <td>3.417</td>
                  <td>
                  <button type="button" class="btn btn-common btn-edit text-center"><i class="fa fa-edit fa-lg"></i></button>
                  <button type="button" class="btn btn-common btn-delete"><i class="fa fa-trash fa-lg"></i></button>
                  </td>
                </tr>
          @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
        

          
        </div>

       
      </section><!-- #services -->
@endsection